<?php
/**
 * Copyright © MagePal. All rights reserved.
 * See COPYING.txt for license details.
 * https://www.magepal.com | support@magepal.com
 */

/** @var $escaper \Magento\Framework\Escaper */
/** @var $block MagePal\GuestToCustomer\Block\Customer\LookupForm */
?>
<form class="form form-edit-account" 
    action="<?= $escaper->escapeUrl($block->getUrl('customer/guesttocustomer/lookupformPost')) ?>" 
    method="post" 
    id="form-validate" 
    data-mage-init='{"validation": {}}'
    data-hasrequired="<?= $escaper->escapeHtmlAttr(__('* Required Fields')) ?>" 
    autocomplete="off">
    <fieldset class="fieldset info">
        <?= $block->getBlockHtml('formkey') ?>
        <legend class="legend"><span><?= $escaper->escapeHtml(__('Guest Order Information')) ?></span></legend><br>
        <div class="field field-order-increment required">
            <label class="label" for="order-increment">
                <span><?= $escaper->escapeHtml(__('Order Number')) ?></span>
            </label>

            <div class="control">
                <input type="text" 
                    id="order-increment" 
                    name="order_increment" 
                    value="" 
                    title="<?= $escaper->escapeHtmlAttr(__('Order Number')) ?>" 
                    class="input-text required-entry" 
                    data-validate="{required: true}" 
                    aria-required="true">
            </div>
        </div>
        <div class="field field-email required">
            <label class="label" for="email">
                <span><?= $escaper->escapeHtml(__('Email')) ?></span>
            </label>

            <div class="control">
                <input type="email" 
                    id="email" 
                    name="email" 
                    value="<?= $escaper->escapeHtmlAttr($block->getCustomer()->getEmail()) ?>" 
                    title="<?= $escaper->escapeHtmlAttr(__('Email')) ?>" 
                    class="input-text" 
                    disabled>
            </div>
        </div>
    </fieldset>

    <?= $block->getChildHtml('form_additional_info') ?>
    
    <div class="actions-toolbar">
        <div class="primary">
            <button type="submit" class="action save primary" title="<?= $escaper->escapeHtmlAttr(__('Save')) ?>"><span><?= $escaper->escapeHtml(__('Save')) ?></span></button>
        </div>
        <div class="secondary">
            <a class="action back" href="<?= $escaper->escapeUrl($block->getBackUrl()) ?>"><span><?= $escaper->escapeHtml(__('Go back')) ?></span></a>
        </div>
    </div>
</form>
