<?php
/**
 * Copyright © MagePal. All rights reserved.
 * See COPYING.txt for license details.
 * https://www.magepal.com | support@magepal.com
 */

/** @var \Magento\Framework\View\Helper\SecureHtmlRenderer $secureRenderer **/
?>

<?php $scriptString = <<<script
    require([
        "jquery",
        "mage/mage"
    ], function($){
        var dataForm = $('#form-validate');
        dataForm.mage('validation', {});
    });
script;
?>
<?= /* @noEscape */ $secureRenderer->renderTag('script', [], $scriptString, false) ?>
